version: "3.9"

services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=local
    healthcheck:
      test: "curl -f http://localhost:8080/heartbeat/readiness || exit 1"
      interval: 20s
      retries: 15
      timeout: 3s
    volumes:
      - ./..:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ns

  mysql:
    build:
      context: ./..
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./../docker/mysql/fixture:/docker-entrypoint-initdb.d
    healthcheck:
      test: "mysql -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} -e 'SELECT 1'"
      interval: 1s
      retries: 15
      timeout: 15s
    networks:
      - ns

networks:
  ns:
    driver: bridge
